### ISSUE TITLE
Do you really need to expose half naked women to showcase your project?

### ISSUE THREAD

**Issue by pirhoo** [liuguangqiang/IPicker#3]
That's sexist and definitely not mandatory to demonstrate how useful is your library.

**Comment by liuguangqiang** [comment]
So sorry, I am not intentionally.There is absolutely no gender discrimination. Just only have these pictures in my phone.I will exclude these screenshots right now.Thanks for your comment.

**Comment by liuguangqiang** [comment]
Yeah, I have changed the screenshots.

**Comment by pirhoo** [comment]
Thanks

**Comment by liuguangqiang** [comment]
Oh no , it’s my reckless, I really thank you.
