### ISSUE TITLE
EventBus消息的区分

### ISSUE THREAD

**Issue by linceln** [liuguangqiang/IPicker#4]
如果A、B两个界面都有选择图片进行上传操作的需求，A Activity 跳转到 B Activity后，B Activity选择的图片在A Activity也能收到消息，导致A误操作。不知道这样描述清楚不，因为EventBus用得不是很熟，不知道有没解决方案？
另外有裁剪功能么？预览图上有，代码里面没找到- -

**Comment by liuguangqiang** [comment]
这里确实有这个问题，现在可以用setOnSelectedListener来获取选择的图片，你可以试试呢，裁剪的功能可以使用， IPicker.setCropEnable(true);

**Comment by linceln** [comment]
我刚才想到一个解决办法，关于`EventBus`的，跳转B Activity时注销A的`EventBus`，这样A就收不到消息了，`onResume()`里面再重新注册，可以保证A自己操作时可以接受到消息。略麻烦，我试下`setOnSelectedListener()`这个。谢谢回复，关了
