### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by ypicoleal** [liuguangqiang/IPicker#5]
Hi buddy i'm currently using this library in a project but i want to change the title and the "done" button to another language how can i change that?

**Comment by liuguangqiang** [comment]
What language do you want?

**Comment by liuguangqiang** [comment]
You could create a strings.xml for another language. https://developer.android.com/training/basics/supporting-devices/languages.html

**Comment by ypicoleal** [comment]
Spanish, what strings i have to translate?

**Comment by ypicoleal** [comment]
Hi buddy, after taken my time to review the project files, finally found the string's xmls, and i could translate it to spanish, thanks pal!!!
