### ISSUE TITLE
导入有问题，帮忙解决一下

### ISSUE THREAD

**Issue by douyn** [liuguangqiang/IPicker#6]
Error:(1, 0) Your project path contains non-ASCII characters. This will most likely cause the build to fail on Windows. Please move your project to a different directory. See http://b.android.com/95744 for details. This warning can be disabled by adding the line 'android.overridePathCheck=true' to gradle.properties file in the project directory.
<a href="openFile:J:\下载\IPicker-master\IPicker-master\app\build.gradle">Open File</a>

**Comment by liuguangqiang** [comment]
是不是你项目的路径包含了中文，你改成英文试试呢
